apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: shopping-cart
  name: shopping-cart
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app.kubernetes.io/name: shopping-cart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shopping-cart
    spec:
      containers:
      - image: shopping-cart
        name: shopping-cart
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  # Assuming your service runs on port 5000
